spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: game-service
              uri: http://game-service
              predicates:
                - Path=/api/spin