apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: casino
build:
  artifacts:
    - image: gateway
      context: services
      jib:
        type: gradle
        project: gateway
        args: [ --no-daemon ]
    - image: game-service
      context: services
      jib:
        type: gradle
        project: game-service
        args: [ --no-daemon ]
    - image: odds-service
      context: services
      jib:
        type: gradle
        project: odds-service
        args: [ --no-daemon ]
      #buildpacks:
      #  clearCache: false
      #  trustBuilder: true
      #  builder: paketobuildpacks/builder-jammy-base
      #  env:
      #    - BP_JVM_VERSION=21
deploy:
  helm:
    releases:
      - name: odds-db
        remoteChart: bitnami/mongodb
        version: 14.4.0
        valuesFiles:
          - infrastructure/mongodb/odds-values.yaml
      - name: prometheus
        remoteChart: bitnami/prometheus
        version: 2.1.2
        valuesFiles:
          - infrastructure/prometheus/values.yaml
manifests:
  rawYaml:
    - services/gateway/k8s.yaml
    - services/game-service/k8s.yaml
    - services/odds-service/k8s.yaml
