apiVersion: apps/v1
kind: Deployment
metadata:
  name: odds-service
  labels:
    app: odds-service
spec:
  selector:
    matchLabels:
      app: odds-service
  template:
    metadata:
      labels:
        app: odds-service
    spec:
      containers:
        - name: odds-service
          image: odds-service
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: odds-service
spec:
  selector:
    app: odds-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
