apiVersion: apps/v1
kind: Deployment
metadata:
  name: odds-service
  labels:
    app: odds-service
spec:
  selector:
    matchLabels:
      app: odds-service
  template:
    metadata:
      labels:
        app: odds-service
    spec:
      containers:
        - name: odds-service
          image: odds-service
          ports:
            - containerPort: 8080
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: odds-service-http
spec:
  selector:
    app: odds-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odds-service-grpc
spec:
  selector:
    app: odds-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 9090
  type: ClusterIP
