spring:
  application:
    name: odds-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:dumb-pass@odds-db-mongodb:27017/mydb?authSource=admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'