spring:
  application:
    name: game
  grpc:
    server:
      enabled: false
  threads:
    virtual:
      enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'